service: massa-sc-scanner-verifier-nest

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x

package:
  excludeDevDependencies: true
  individually: true
  patterns:
    - '!node_modules/**'
    - '!src/**'
    - '!**/.git/**'
    - 'dist/**'

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /
          cors: true
      - http:
          method: ANY
          path: '{proxy+}'
          cors: true
