service: massa-sc-scanner-verifier

# plugins:
#   - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x

package:
  excludeDevDependencies: true
  individually: true
  exclude:
    - test/**
    - .gitignore
    - package-lock.json
    - .git/**
    - '*.md'
    - .aws

functions:
  main:
    handler: dist/serverless/handler.handler
    events:
      - http:
          method: ANY
          path: /
          cors: true
      - http:
          method: ANY
          path: '{proxy+}'
          cors: true

  inspect:
    handler: dist/serverless/inspect.handler
    events:
      - http:
          method: GET
          path: /inspect
          cors: true
