service: massa-sc-scanner-verifier

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  timeout: 900

package:
  excludeDevDependencies: true
  individually: true
  patterns:
    - '!node_modules/**'
    - '!src/**'
    - '!**/.git/**'
    - 'dist/**'

functions:
  scanner:
    handler: dist/scanner.handler
    events:
      - http:
          method: GET
          path: /scan-from-massexplo
          cors: true
      - http:
          method: GET
          path: /scanner # https://akb6wfr7s9.execute-api.us-east-1.amazonaws.com/dev/scanner?address=AS1pBvN6cMKEEBwFfpQNmfY6hT85XcL2VzJSuAFeHt5Ybvbo7mb&chainId=77658366
          cors: true
      - http:
          method: GET
          path: /wat # https://akb6wfr7s9.execute-api.us-east-1.amazonaws.com/dev/wat?address=AS1pBvN6cMKEEBwFfpQNmfY6hT85XcL2VzJSuAFeHt5Ybvbo7mb&chainId=77658366
          cors: true
      - http:
          method: GET
          path: /wasm # https://akb6wfr7s9.execute-api.us-east-1.amazonaws.com/dev/wasm?address=AS1pBvN6cMKEEBwFfpQNmfY6hT85XcL2VzJSuAFeHt5Ybvbo7mb&chainId=77658366
          cors: true
  verifier:
    handler: dist/verifier.handler
    events:
      - http:
          method: POST
          path: /verify # https://akb6wfr7s9.execute-api.us-east-1.amazonaws.com/dev/verify
          cors: true
          timeout: 50000
      - http:
          method: GET
          path: /verified # https://akb6wfr7s9.execute-api.us-east-1.amazonaws.com/dev/verified?address=AS1pBvN6cMKEEBwFfpQNmfY6hT85XcL2VzJSuAFeHt5Ybvbo7mb&chainId=77658366
          cors: true
      - http:
          method: GET
          path: /zip # https://akb6wfr7s9.execute-api.us-east-1.amazonaws.com/dev/zip?address=AS1pBvN6cMKEEBwFfpQNmfY6hT85XcL2VzJSuAFeHt5Ybvbo7mb&chainId=77658366
          cors: true
